version: "2"

services:
  frontend:
    image: squadgoals-frontend
    environment:
      - REACT_APP_BACKEND_HOST
    restart: always
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    links:
      - backend
    networks:
      - squadgoalsnetwork

  backend:
    image: squadgoals-backend
    depends_on:
      - postgres
    restart: always
    environment:
      - DB_HOST
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    networks:
      - squadgoalsnetwork

  postgres:
    image: postgres:12.2
    volumes:
      - data:/var/lib/postgres/data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: squadgoals
    networks:
      - squadgoalsnetwork
    ports:
      - "35432:5432"

  cowsay:
    image: grycap/cowsay:latest
    depends_on:
      - frontend
    command: /usr/games/cowsay -f dragon "Hey hey hey! Hey hey hey! Hey hey hey! Whatsawhatsawhatsawhatsawhatsawhatsawhatsa up SquadGoals! Hey hey hey everybody my name is Carlos Matos and I am coming from Quebec City, Quebec and let me tell you guys that I am so excited, I am so happy, I am really so thrilled to be right now sharing this amazing, glorious, super, and exciting moment of my life with all of you guys, and let me tell you that we are really changing the world as we know it, the world is not anymore the way it used to be, mmm mmm, No! No! No! SQUAD GOALS! Wow! SQUAD GOALS!"

networks:
  squadgoalsnetwork:
    driver: bridge

volumes:
  data: {}
