version: "2"

services:
  frontend:
    image: squadgoals-frontend
    restart: always
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    links:
      - backend
    networks:
      - squadgoalsnetwork

  backend:
    image: squadgoals-backend
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    networks:
      - squadgoalsnetwork

networks:
  squadgoalsnetwork:
    driver: bridge
