version: "2"

services:
  frontend:
    image: squadgoals-frontend
    environment:
      - REACT_APP_BACKEND_HOST
    restart: always
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    links:
      - backend
    networks:
      - squadgoalsnetwork

  backend:
    image: squadgoals-backend
    depends_on:
      - postgres
    restart: always
    environment:
      - DB_HOST
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    networks:
      - squadgoalsnetwork

  postgres:
    image: postgres:12.2
    volumes:
      - data:/var/lib/postgres/data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: squadgoals
    networks:
      - squadgoalsnetwork
    ports:
      - "35432:5432"

networks:
  squadgoalsnetwork:
    driver: bridge

volumes:
  data: {}
